# Generated by Django 4.1.7 on 2023-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('secondname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
    ]
