# Generated by Django 4.1.7 on 2023-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviedatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('language', models.CharField(choices=[('te', 'telugu'), ('en', 'english'), ('ta', 'tamil'), ('hn', 'hindi'), ('ka', 'kanada')], max_length=2)),
                ('category', models.CharField(choices=[('ac', 'action'), ('rc', 'romance'), ('co', 'comedy'), ('hr', 'horror'), ('ad', 'adventures'), ('ms', 'mystery'), ('th', 'thriller')], max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='moviedatails')),
            ],
        ),
    ]
