# Generated by Django 4.1.7 on 2023-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_alter_moviedatails_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedatails',
            name='videofile',
            field=models.FileField(null=True, upload_to='moviedetails'),
        ),
    ]
