# Generated by Django 4.1.7 on 2023-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0008_moviedatails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedatails',
            name='cast',
            field=models.CharField(default='', max_length=255),
        ),
    ]
