# Generated by Django 4.1.7 on 2023-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0009_moviedatails_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatails',
            name='cast',
            field=models.TextField(default=''),
        ),
    ]
