# Generated by Django 4.1.7 on 2023-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0010_alter_moviedatails_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedatails',
            name='viedo',
            field=models.FileField(default='', upload_to='movieviedo'),
        ),
    ]
