# Generated by Django 4.1.7 on 2023-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0014_alter_regestration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regestration',
            name='email',
            field=models.EmailField(default='', max_length=64, unique=True),
        ),
    ]
