# Generated by Django 4.1.7 on 2023-05-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0019_alter_regestration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='regestration',
            name='subscription',
            field=models.CharField(default='not subscribe', max_length=64),
        ),
    ]
