# Generated by Django 4.1.7 on 2023-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0022_alter_regestration_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regestration',
            name='subscription',
            field=models.CharField(default='notsubscribe', max_length=64),
        ),
    ]
