# Generated by Django 4.1.7 on 2023-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0023_alter_regestration_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatails',
            name='image',
            field=models.ImageField(default='', upload_to='moviedatails/%y'),
        ),
        migrations.AlterField(
            model_name='moviedatails',
            name='viedo',
            field=models.FileField(default='', upload_to='play//%y'),
        ),
    ]
