# Generated by Django 4.1.7 on 2023-10-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0024_alter_moviedatails_image_alter_moviedatails_viedo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regestration',
            name='subscription',
        ),
    ]
